# Handling Imbalanced Dataset

A data is said to be Imabalanced dataset when there is big gap between the number of zeroes and number of ones.

class 0 : 10000<br> 
class 1 : 100

Undersampling : It will bring down the number of class 0. by reducing the dataset. That's why don't use this until unless, the dataset is very small.

Oversampling : It will bring the class 1 samples up by adding more data points or repeating the existing points.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("D:/Datasets/creditcard.csv")

In [4]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [14]:
df['Class'].unique()

array([0, 1], dtype=int64)

In [5]:
df.shape

(284807, 31)

In [6]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# dependent Feature
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
#### Indepedent and dependent features
x = df.drop('Class',axis=1)
y = df['Class']

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.7)

In [11]:
log_class = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3),
        'penalty':['l1','l2']}
cv = KFold(n_splits = 5,shuffle = False,random_state = None)

In [12]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')

In [13]:
clf.fit(x_train,y_train)

C:\Users\sarth\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:925: UserWarning: One or more of the test scores are non-finite: [       nan 0.7982096         nan 0.84004792        nan 0.819546
        nan 0.82771442        nan 0.83324633]
  category=UserWarning
C:\Users\sarth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [15]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
clf.score(x_test,y_test)

0.8508586334384277

In [17]:
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("Accuracy Score \n",accuracy_score(y_test,y_pred))
print("Classification Report\n", classification_report(y_test,y_pred))

Confusion Matrix 
 [[198927     70]
 [   131    237]]
Accuracy Score 
 0.9989917989617034
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    198997
           1       0.77      0.64      0.70       368

    accuracy                           1.00    199365
   macro avg       0.89      0.82      0.85    199365
weighted avg       1.00      1.00      1.00    199365



In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [20]:
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("Accuracy Score \n",accuracy_score(y_test,y_pred))
print("Classification Report\n", classification_report(y_test,y_pred))

Confusion Matrix 
 [[198968     29]
 [    94    274]]
Accuracy Score 
 0.9993830411556692
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    198997
           1       0.90      0.74      0.82       368

    accuracy                           1.00    199365
   macro avg       0.95      0.87      0.91    199365
weighted avg       1.00      1.00      1.00    199365



#### Under Sampling
- Reduce the points of the maximum labels.
- **Use only this when there is very less data**

In [22]:
from collections import Counter
from imblearn.under_sampling import NearMiss

In [23]:
 y_train.value_counts()

0    85318
1      124
Name: Class, dtype: int64

In [27]:
ns=NearMiss(0.8)
X_train_ns,y_train_ns = ns.fit_resample(x_train,y_train)
print('The number of class before the fit{}'.format(Counter(y_train)))
print('The number of class after the fit{}'.format(Counter(y_train_ns)))

C:\Users\sarth\anaconda3\lib\site-packages\imblearn\utils\_validation.py:591: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning,


The number of class before the fitCounter({0: 85318, 1: 124})
The number of class after the fitCounter({0: 155, 1: 124})


In [28]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [31]:
y_pred = classifier.predict(x_test)
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("Accuracy Score \n",accuracy_score(y_test,y_pred))
print("Classification Report\n", classification_report(y_test,y_pred))

Confusion Matrix 
 [[161746  37251]
 [    27    341]]
Accuracy Score 
 0.8130163268377097
Classification Report
               precision    recall  f1-score   support

           0       1.00      0.81      0.90    198997
           1       0.01      0.93      0.02       368

    accuracy                           0.81    199365
   macro avg       0.50      0.87      0.46    199365
weighted avg       1.00      0.81      0.90    199365



The accuracy has gone way down

# Oversampling


In [38]:
from imblearn.over_sampling import RandomOverSampler

In [39]:
os=RandomOverSampler(0.5)
X_train_os,y_train_os = os.fit_resample(x_train,y_train)
print('The number of class before the fit{}'.format(Counter(y_train)))
print('The number of class after the fit{}'.format(Counter(y_train_os)))

C:\Users\sarth\anaconda3\lib\site-packages\imblearn\utils\_validation.py:591: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning,


The number of class before the fitCounter({0: 85318, 1: 124})
The number of class after the fitCounter({0: 85318, 1: 42659})


In [42]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_os,y_train_os)

RandomForestClassifier()

In [44]:
y_pred = classifier.predict(x_test)
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("Accuracy Score \n",accuracy_score(y_test,y_pred))
print("Classification Report\n", classification_report(y_test,y_pred))

Confusion Matrix 
 [[198974     23]
 [   104    264]]
Accuracy Score 
 0.9993629774534146
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    198997
           1       0.92      0.72      0.81       368

    accuracy                           1.00    199365
   macro avg       0.96      0.86      0.90    199365
weighted avg       1.00      1.00      1.00    199365



# SMOTETomek
Both Under and over sampling

In [46]:
from imblearn.combine import SMOTETomek

In [48]:
os=SMOTETomek(0.5)
X_train_os,y_train_os = os.fit_resample(x_train,y_train)
print('The number of class before the fit{}'.format(Counter(y_train)))
print('The number of class after the fit{}'.format(Counter(y_train_os)))

The number of class before the fitCounter({0: 85318, 1: 124})
The number of class after the fitCounter({0: 84586, 1: 41927})


In [49]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_os,y_train_os)

RandomForestClassifier()

In [50]:
y_pred = classifier.predict(x_test)
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("Accuracy Score \n",accuracy_score(y_test,y_pred))
print("Classification Report\n", classification_report(y_test,y_pred))

Confusion Matrix 
 [[198953     44]
 [    78    290]]
Accuracy Score 
 0.9993880570812329
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    198997
           1       0.87      0.79      0.83       368

    accuracy                           1.00    199365
   macro avg       0.93      0.89      0.91    199365
weighted avg       1.00      1.00      1.00    199365

